### ISSUE TITLE
Upgrade to v2.x results in 20+ load and 100% cpu usage

### ISSUE THREAD

**Issue by ricuss** [Webklex/php-imap#100]
Hi @Webklex 

For production we have a server with 32GB of RAM and 4vCPU's. 

This server has been syncing 1000 folders every 2-3 minutes with no problem (using laravel's queue system and about 150 workers), RAM usage about 50-60% and CPU running at about 50 as well.

When upgrading to v2.x, the biggest changes came in with the namespaces and how we connect, but the syncing process still remained the same on my side:

1. Make connection
2. Get messages for folder
3. Loop over messages to process them
4. close connection

`->all()` also had to be added to the query along with the existing limit, as without this it seemed like no messages were getting returned, the query run for all these mailboxes are relatively straightforward, basically `$folder->query()->setFetchBody(false)->all()->limit(10)->get()`

When the version 2 update was deployed to production, we instantly started getting 20+ load on the server and 100% cpu usage. The specs on the server did not change, only the version of webklex/php-imap and webxklex/laravel-imap

From the below image you can see the spikes to 100% cpu usage whenever the sync got enabled 

![image](https://user-images.githubusercontent.com/17425015/107175884-9e9ded80-69d6-11eb-878f-cbcbaa9227a1.png)

![image](https://user-images.githubusercontent.com/17425015/107175967-d311a980-69d6-11eb-822b-95ea667cb140.png)

I had to revert back to v1 as I could not pinpoint why this was happening all of a sudden, with the only change being to the version of the package.

I tested on both a digital ocean and aws server with the same results, as soon as I enable v2 the server gets destroyed.

Do you have any idea what could be causing this drastic change in resource usage between the versions? Should I maybe not be calling `->all()` even though I limit? Anything obvious you think I might have missed that could cause this when upgrading?

**Comment by ricus-zero2one** [comment]
Hi @Webklex 

Any idea on this one?

**Comment by Webklex** [comment]
Hi @ricus-zero2one ,
thanks for your report. 

I honestly don't know. I'm unable to reproduce this behavior.
Using `Query::all()` in general might be a bad idea - you'll fetch every available message. Try to limit the amount to only those ones you are actually interesting in. Using `Query::since()` might help :)

Additional information and available search criteria: https://www.php-imap.com/api/query

Best regards,

**Comment by ricus-zero2one** [comment]
@Webklex The reason I added the all() was because just get() wasn't returning the results. But I think that might be the reason for the high resource usage if all() will def get all available emails.

What I want to do, is get the latest x amount of emails. On v1 I used the below:

`$folder->query()->setFetchBody(false)->limit(10)->get()`

But on v2 this doesn't return anything anymore, and that's when I added the all() as it then returned the emails. But I think me using limit in conjunction with all(), was resulting in it "seemingly" working as expected, because I would only get the x amount of emails, but behind the scenes it's requesting all of them?

My goal is simply to get the latest x amount of emails, what would be the v2 way to achieve this in the most efficient way? 

I thought that `->get()` would execute the query, but that doesn't seem to be the case with only limit being applied. Given the following: `$folder->query()->limit(5)->get();` the result is just null as nothing seems to have been sent to the imap server yet:

![image](https://user-images.githubusercontent.com/17425015/108309014-758d1200-71b9-11eb-915a-16535a54a568.png)


If I add the `since()`, so now having `$folder->query()->since(now()->subDay())->limit(5)->get()` I do get the expected result:

![image](https://user-images.githubusercontent.com/17425015/108309138-abca9180-71b9-11eb-91cd-3aae4665ad30.png)

However this seems like it will query all mails in the last day, so lets say for argument sake 200 for a busy mailbox, but then I only grab the latest 5 of that. With this I still queried way more than I need to.

Is there not a simple way to just get last x message in a mailbox? without querying more than I need and?

Regards

**Comment by Webklex** [comment]
Hi @ricuss ,
please update to the latest release (>=3.2.0). There have been a lot of improvements :)

Feel free to reopen this issue if the problem persists.

Best regards,

**Comment by ricuss** [comment]
Thanks @Webklex , I wasn't aware there is a new version 3, we are still running v1 in production (it's still syncing thousands of mailboxes every day without problem 👍  )

I'll take a stab at upgrading to v3 when I get a chance, thanks for the great work on this package!!
