### ISSUE TITLE
Get message by unique id

### ISSUE THREAD

**Issue by jane08** [Webklex/php-imap#279]
Hi) I got message with msgn and everything worked fine
   `$message = $folder->query()->unseen()->getMessage($letter->msgn);`
until I came across a case when msgn for a few messages in one mailbox were the same.
 So msgn is not unique. And I've also read that uid is not unique either. It seems like message_id should be unique but I couldn't find any method to get a message by message_id.
The problem is with msgn is that I can accidently delete a wrong message if a few messages have the same msgn.
So the question is what is the best way to get correct message? Using what parameter I can get correct message?

**Comment by Webklex** [comment]
Hi @jane08 ,
you are absolutely correct. None of those values is unique and can be used to reliably identify the message.
Here is a similar thread from some time ago on the same subject: https://github.com/Webklex/laravel-imap/issues/269

You'll need to track / compare multiple values in order to reasonably assume you've got the same message. However there will always be a chance that you've got the wrong message. That's just how "email" is build - unless your provider is adding a custom header containing a real unique id.

Best regards & happy coding,

**Comment by jane08** [comment]
@Webklex thank you
