### ISSUE TITLE
Bugs with credentials

### ISSUE THREAD

**Issue by KyoRion** [Webklex/php-imap#30]
This's my code 
![image](https://user-images.githubusercontent.com/26852023/95978087-e60ad780-0e43-11eb-8ac8-5eb98f2eb5f0.png)
Just forgot username & password I'd replace to null for cap picture
when run and check connect() 
I got this in my console
![image](https://user-images.githubusercontent.com/26852023/95978206-10f52b80-0e44-11eb-8c2b-b2c24c371d6a.png)
and here my view
![image](https://user-images.githubusercontent.com/26852023/95978253-1d798400-0e44-11eb-8194-57e5d0e92180.png)

**Comment by Webklex** [comment]
Hi @KyoRion ,
thanks for your report. The extra challenge you received, is the base64 encoded response. If you decode it, you'll receive something like this:
```json
{"status":"400","schemes":"Bearer","scope":"https://mail.google.com/"}
```
which indicates a problem with the provided credentials. Since you are using gmail, you could also switch to an "Application password" if you are having trouble to obtain an access token. See the [wiki](https://github.com/Webklex/php-imap/wiki/Google-Mail---Gmail#connect-using-an-application-password) entry for a setup guide.

Best regards,
