### ISSUE TITLE
Forwarded Email Inline attachment missing

### ISSUE THREAD

**Issue by perumurugan12** [Webklex/php-imap#329]
scenario 1:
while read forwarded email inline attachment image are missing.
$message->hasAttachments(); it will return true.

scenario 2:
Email have attachment,text content and inline images

$message->hasTextBody();
$message->hasHTMLBody();

both method return false.

how to get message body content including inline images.

**Comment by Webklex** [comment]
Hi @perumurugan12 ,
many thanks for your report.

I'm missing some information though in order to look into it. Please take a look at https://github.com/Webklex/php-imap/issues/new?assignees=&labels=&template=bug_report.md to get a sense for all the required and useful information to tackle an issue. 

Especially the required code / email required to cause this issue.

 Best regards & happy coding,

**Comment by kben** [comment]
Hi,

I had the same issue. I fixed it by modifying Part.php and check for '$this->disposition == "inline"':
```
    public function isAttachment(): bool {
        $valid_disposition = in_array(strtolower($this->disposition ?? ''), ClientManager::get('options.dispositions'));

        if ($this->type == IMAP::MESSAGE_TYPE_TEXT && ($this->ifdisposition == 0 || empty($this->disposition) || !$valid_disposition || $this->disposition == "inline")) {
            if (($this->subtype == null || in_array((strtolower($this->subtype)), ["plain", "html"])) && $this->filename == null && $this->name == null) {
                return false;
            }
        }
        return true;
    }
```
