### ISSUE TITLE
Can't connect to Outlook OAuth IMAP

### ISSUE THREAD

**Issue by Dhavalptel** [Webklex/php-imap#374]
**Describe the bug**
Connection setup failed

**Used config**
```
    $guzzleClient = new guzzleClientClass();
    $response = $guzzleClient->post(
        'https://login.microsoftonline.com/TENANTID/oauth2/v2.0/token',
        [
            "headers" => [
                "Accept" => "application/json"
            ],
            'form_params' => [
                'client_id' => CLIENTID,
                'client_secret' => CLIENT SECRET,
                'grant_type' => 'password',
                'scope' => 'https://graph.microsoft.com/.default',
                'username' => USERNAME,
                'password' => PASSWORD
            ]
        ]
    );
    $body = json_decode($response->getBody()->getContents(), true);
    if ($body['access_token']) {
        $cm = new ClientManager();
        $client = $cm->make([
            'host' => 'outlook.office365.com',
            'port' => 993,
            'encryption' => 'ssl', // 'tls',
            'validate_cert' => true,
            'username' => USERNAME,
            'password' => $body['access_token'],
            'protocol' => 'imap',
            'authentication' => "oauth",
        ]);

        $client->connect();
        dd($client);
```
**Screenshots**
![image](https://user-images.githubusercontent.com/26641666/218386917-b6920549-8fc7-4aa9-9038-7714940afa2c.png)

![image](https://user-images.githubusercontent.com/26641666/218387127-647a0f56-dff5-4ffb-922c-36f9b1342e60.png)

**Additional context**
I'm using the version 
```
"webklex/php-imap": "^4.1
```

Please let me know if I'm missing something.
Thanks in advance

**Comment by vagkaefer** [comment]
Hello @Dhavalptel ,

I confess that I struggled to make this integration work with Outlook.

But this link helped a lot: https://stackoverflow.com/questions/73370661/php-connect-mailbox-office-365-with-oauth

I used a few minutes ago version 4.1 and 5.0, both working normally

Please check the step by step indicated in the link, you will probably be able to make it work right

**Comment by Dhavalptel** [comment]
@vagkaefer I've resolved it by adding the below scope to obtain access token.
```
https://outlook.office.com/.default
```

**Comment by vagkaefer** [comment]
Nice, I'm glad it's solved, thanks for sharing your solution ;D

**Comment by timmetj** [comment]
@Dhavalptel can you show/edit above code? I'm also struggling to get this working using the [App-only](https://learn.microsoft.com/en-us/azure/active-directory/develop/permissions-consent-overview#access-scenarios) access and the grant_type set to client_credentials in my case
I used both https://outlook.office.com/.default or https://graph.microsoft.com/.default scopes (i can not add both?) token is returned but always keep getting same connection setup failed message.

I think maybe the examples/docs should also update since i think the oAuth of microsoft is changed in last months now allowing to use this [client flow](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow)

Maybe i'm missing some some settings in my Azure app..

**Comment by Dhavalptel** [comment]
@timmetj Here is the working example with `client_credentials`
```
        $guzzle = new guzzleClient();
        $response = $guzzle->post(
            'https://login.microsoftonline.com/'.env('AZURE_TENANT_ID').'/oauth2/v2.0/token',
            [
                "headers" => [
                    "Accept" => "application/json"
                ],
                'form_params' => [
                    'client_id' => env('AZURE_CLIENT_ID'),
                    'client_secret' => env('AZURE_CLIENT_SECRET'),
                    'grant_type' => 'client_credentials',
                    'scope' => 'https://outlook.office.com/.default',
                ]
            ]
        );
        $body = json_decode($response->getBody()->getContents(), true);
        if ($body['access_token']) {
            $cm = new ClientManager();
            $client = $cm->make([
                'host' => 'outlook.office365.com',
                'port' => 993,
                'encryption' => 'ssl',
                'validate_cert' => true,
                'username' => env('IMAP_USERNAME'),
                'password' => $body['access_token'],
                'protocol' => 'imap',
                'authentication' => "oauth",
            ]);

            $client->connect();
        }

**Comment by timmetj** [comment]
@Dhavalptel thanks. i have exactly this also yes (only using CURL instead of guzzle to fetch acces_token but same) I guess maybe some config is wrong in azure itself.. i have enabled like almost all email related permissions, also all in your screenshot except pop, maybe i also need those? But we're using imap?

And you don't have a redirect_url specified? Since this is not needed normally for client-flow?
![image](https://user-images.githubusercontent.com/5031746/219665144-07600309-55e9-4555-afb1-515bc42e1965.png)

You also didn't use any authorize calls first?
![image](https://user-images.githubusercontent.com/5031746/219665404-0a61bd28-97e1-4a84-b9e1-ee0e8674d91e.png)

**Comment by tiamatloc** [comment]
@timmetj Have you set up your service principle and mapped it to the mailbox? Using a client_credentials grant will allow you to authenticate to Azure, but it doesn't grant you access to the mailboxes themselves (if it did you could read all mailboxes!). Once your app registration is created you must create the service principle using the object ID of the Enterprise app (not app registration!) using Powershell and then grant the service principle access to the mailbox like you would grant delegate access to the mailbox for another user (e.g. Bob needs access to Alice's email whilst Alice is on vacation).

This is a good example https://vielhuber.de/en/blog/access-with-php-to-exchange-office-365/

**Comment by timmetj** [comment]
ok thanks, will have a look to this.
