### ISSUE TITLE
getFolder('INBOX.Sent') does not work

### ISSUE THREAD

**Issue by freescout-helpdesk** [Webklex/php-imap#380]
This works and returns a folder:
```
$client->getFolder('Sent');
```
This does not work:
```
$client->getFolder('INBOX.Sent');
```

According to the documentation both ways should work: https://www.php-imap.com/api/client

![2023-02-23_09-31-42](https://user-images.githubusercontent.com/40499291/220835206-57868b9c-aa8b-46e6-afe6-16c3c5820efe.png)

**Comment by craigpotter** [comment]
I am fairly sure it depends on the folder naming on the IMAP server. Get all the folders and check out the folder naming. Things like Outlook/Microsoft don't use the `INBOX.` naming

**Comment by Webklex** [comment]
Hi @freescout-helpdesk ,
please try to use a different delimiter such as `/`. Some provider use a `/` instead of a `.` to describe a folder / mailbox path.

You can change the default delimiter inside your config: https://github.com/Webklex/php-imap/blob/master/src/config/imap.php#L145
This might be necessary if you want to use methods which rely on the correct delimiter.

I hope this helps.

Best regards,

**Comment by freescout-helpdesk** [comment]
We've ended up simply using `$client->getFolderByPath('INBOX.Sent')`. It works.
