### ISSUE TITLE
Solution for empty body issue

### ISSUE THREAD

**Issue by freescout-helpdesk** [Webklex/php-imap#397]
Maybe this info have not reached @webklex by email, so we are posting it here.

This line https://github.com/Webklex/php-imap/blob/master/src/Message.php#L906 on some systems actually throws `"iconv(): Wrong encoding, conversion from "ISO-8859-1" to "UTF-8//IGNORE" is not allowed"` error. But it's suppressed via "@".

On some systems "iconv" works with "//IGNORE" on some without. So here is the solution:
```
            try {
                return iconv($from, $to.'//IGNORE', $str);
            } catch (\Exception $e) {
                return @iconv($from, $to, $str);
            }
```
https://github.com/freescout-helpdesk/freescout/blob/master/overrides/webklex/php-imap/src/Message.php#L727

Now we don't have an "empty body" issue anymore in our project.

**Comment by Webklex** [comment]
Hi @freescout-helpdesk ,
many thanks for your report and great suggestion! I'm a bit afraid though of removing `iconv` and switching to purely relying on `mb_convert_encoding` instead. This is mainly caused by a lack of "testability" _(Testbarkeit)_ on my end. Any idea how I could setup a testing environment for this - especially for the test-docker container?

Best regards and happy coding,
