### ISSUE TITLE
[Question] Queue retrieval of all emails

### ISSUE THREAD

**Issue by Max13** [Webklex/php-imap#42]
In my current project, I need to constantly download a copy of every email in a folder and without necessarily changing anything on downloaded emails. Locally (in my app), I will process them.

It's up to my user to move the email, set it read or delete it (after local processing), and a folder may contain a large number of messages.

In term of connections, efficiency, calls, memory, speed, etc… Is it better to open a single connection, process emails in ascending order one by one locally, saving the already processed `Message-ID` (to avoid processing them twice in case of a crash), or is it better to connect once, download like 50 or 100 messages, process them and reconnect each time when necessary (if the processing implies changing a flag or moving a message) ?

**Comment by Webklex** [comment]
Hi @Max13 ,
it depends on your setup and available system resources but I guess that's not really helpful. 

So here wo go:
I would recommend to set "`fetch_body`" to `false` in order to reduce the amount of data you are requesting. If you've validated the "message_id" and you indeed require the body, just call `$message->parseBody()` to load it afterwards. This should greatly decrease the loading time.

If you fetch a message, the entire message is stored in memory - if you only fetch headers, I guess its save to fetch 10.000+ at once. If you are fetching the complete message, be careful. An email can (even if it's unlikely) reach several gb in size.

Regarding the speed: Avoid unnecessary calls / requests is always a good thing. You could take a look at the `Webklex\PHPIMAP\Connection\Protocols\ImapProtocol::class` and perhaps chain certain requests. You can usually provide a range of uids / msgn like `10:14` (all messages from msgn 10 to 14) instead of a single msgn if you want to apply an action to several messages at once and therefor save some requests.

I'll hope this answers some of your questions :)

Best regards,

**Comment by Max13** [comment]
Thanks for your input @Webklex

> I would recommend to set "fetch_body" to false in order to reduce the amount of data you are requesting

I already have set `fetch_body` and `fetch_flags` to `false`. So we agree on that.

> if you only fetch headers, I guess its save to fetch 10.000+ at once

Well... I dumped at the beginning of the `each` in `Query::get()`. I'm fetching 2 or 3 messages per seconds, on gmail and using my home connection (may be the setup). The folder I'm testing with contains 2700+ messages and I receive a new email in this folder every hour or 30 min. So by the time I arrive at 1000, I have new emails which won't be checked (as, during the each, there is already a fixed number of messages to be fetched). And ultimately, this isn't a big deal, I can start again and skip already processed message-ids.

I'm hesitating between saving a batch to process locally (which may imply connecting again if the message needs to be touched) and simply stay connected and process 1 by 1 until it stops (crash or finish).

> You can usually provide a range of uids / msgn like 10:14 (all messages from msgn 10 to 14) instead of a single msgn

As I see, even by fetching only headers, `Query::get()` will do 1 call for each message. Are you saying that it's possible to get a range of messages with only 1 call, or are you referring to pagination for instance (which is not technically "providing a range" but works the same)?

Thank you for your answers, they certainly opens some doors

**Comment by Webklex** [comment]
Try to call `ImapProtocol::headers($sequence="10:14")`. 
This should return all raw headers for the messages 10 to 14. However I haven't tested it, but it should work in theory.

Best regards,

**Comment by Max13** [comment]
Hey again Webklex,
During the night, I had an idea and read about gmail limits… Is there currently (or doable) way to idle a folder and receive only the headers in the callback? Looking at the code, it's possible to get an empty event (without fetching the email) at least.

I can `IDLE` X folders and queue the action delayed for 30 minutes and stop ``

**Comment by Webklex** [comment]
Hi @Max13 ,
yes there is.

You could disable the options for "fetch_body". That way what ever you do afterwards won't fetch the body by default :)
However I don't think its possible to idle on more than one folder at the same time over the same connection. But this is just my guess. To be honest and clear - I haven't tested it. Please proof me wrong :) Anyway by only fetching the message headers and over a period of < 30min I think you are perfectly fine to do so, unless you are expecting huge amounts of messages to come in (>10k). Then it might geht a bit tricky..

Best regards,
