### ISSUE TITLE
How to attach image

### ISSUE THREAD

**Issue by edersonmartinsv** [Webklex/php-imap#425]
How to attach image in the body of the email.
Where has 'cid:image' change to full url attachment image

**Comment by edersonmartinsv** [comment]
@Webklex please it is possible ?

**Comment by edersonmartinsv** [comment]
Hi?

**Comment by tiamatloc** [comment]
@edersonmartinsv I'm not sure I quite understand, are you trying to turn cid:image into something like /path/to/image.png? If so that isn't really something for the library to do, that's for your own code. After saving the images to disk you would want something like this. Note that this is fairly rough code and doesn't really have any error handling.

`preg_match_all('/src="cid:(.*)"/Uims', $emailBody, $matches);`
`if (count($matches))`
`{`
`  $search = array();`
`  $replace = array();`
`  foreach ($matches[1] as $match)`
`  {`
`    $attFilename = '';`
`    foreach ($attachments as $attachment)`
`    {`
`      if ($attachment->getDisposition() === 'inline' && $attachment->getId() === $match) $attFilename = $attachment->getName();`
`    }`
`  }`
`  $search[] = 'src="cid:' . $match . '"';`
`  $replace[] = 'src="/path/to/' . $attFilename . '"';`
`}`
`$emailBody = str_replace($search, $replace, $emailBody);`

**Comment by edersonmartinsv** [comment]
I'm sorry my English/translator (Google) is horrible.

Thank you very much, I needed this answer
