### ISSUE TITLE
Get list of modified messages from server

### ISSUE THREAD

**Issue by sazanof** [Webklex/php-imap#426]
**Hello!**
Please tell me, is there any way to get a list of modified messages from server? 

For example: through a third-party mail client or a browser version of mail app, a new tag or label was added to the message, or message moved to another folder, or trashed - and using **php-imap** without scanning the entire Folder to understand which messages were changed? 

**Thanks!**

**Comment by skurrilewelt** [comment]
Good question. Would be great, if this could be done.

**Comment by Webklex** [comment]
HI @sazanof ,
this is an excellent question.

Short answer: no its not supported by the imap protocol.

Long answer: it depends...
Lets assume you are using a google mail account. If you use their browser email client, they don't rely on the imap protocol to display your data, such as folders and messages. They can access / query their db etc. But how are thunderbird, outlook, etc doing it? Well you likely have an option somewhere which configures the "fetch interval" as well as the option to subscribe / monitor certain folders. The client will fetch these folders and their contents in a defined interval in order to make sure they are up to date.
The mail server doesn't keep track of what a client has fetched before. You can only query the server and "ask" for the current state. 

However, you could explore the `$folder->idle()` and `$folder->subscribe()` methods and see if the real time information you receive is enough for your use case.

Have a great day and happy coding,

**Comment by sazanof** [comment]
Thanks! I looked at different mail clients, how it is implemented in them. In fact, if the UI has a list of emails that was previously uploaded / synchronized, we can pass UIDs to the SEARCH, and work with that result. This is a good alternative.

**Comment by Webklex** [comment]
Keep in mind that uids as well as sequence ids aka message ids are not unique and can change.

**Comment by sazanof** [comment]
I think we can close the question, since everything is quite clear
